on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push (Master)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader --no-dev

      - name: Install Node dependencies
        run: |
          npm install
          npm update
          npm audit fix

      - name: Run additional Composer commands
        run: |
          composer dump-autoload
          composer update --prefer-stable --optimize-autoloader --no-dev

      - name: Run migrations
        run: php artisan migrate --force --no-interaction

      - name: Compile assets
        run: npm run production

      - name: Run Laravel optimization commands
        run: |
          php artisan optimize
          php artisan optimize:clear
          php artisan cache:clear
          php artisan optimize
          php artisan config:cache
          php artisan event:cache
          php artisan route:cache
          php artisan view:cache

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SSH_SERVER }}
          ssh-port: ${{ secrets.SSH_PORT }}
          remote-user: ${{ secrets.SSH_USER }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: ${{ secrets.SSH_PATH }}
          rsync-options: --delete-after --exclude=.env --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore
          
