on:
  push:
    branches:
      - master
name: 🚀 Deploy website (Server) on push (Master)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Node dependencies and build assets
        run: |
          npm install
          npm update
          npm audit
          npm audit fix --force
          npm run build

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SSH_SERVER }}
          ssh-port: ${{ secrets.SSH_PORT }}
          remote-user: ${{ secrets.SSH_USER }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: ${{ secrets.SSH_PATH }}
          rsync-options: --delete-after --recursive --exclude '.env' --exclude '.git*' --exclude '.git/' --exclude 'README.md' --exclude 'readme.md' --exclude '.gitignore' --exclude 'storage/app' --exclude 'storage/framework' --exclude 'storage/logs'

      - name: Run Composer and Laravel commands on server via Remote SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_PATH }}
            composer2 install --no-progress --no-suggest --no-interaction --optimize-autoloader --no-dev
            composer2 dump-autoload
            composer2 update --prefer-stable --optimize-autoloader --no-dev --no-suggest
            php artisan migrate --force --no-interaction
            php artisan optimize
            php artisan optimize:clear
            php artisan cache:clear
            php artisan optimize
            php artisan config:cache
            php artisan event:cache
            php artisan route:cache
            php artisan view:cache
