name: Psalm Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 16 * * 6' # Every Saturday at 16:00 UTC, which is Sunday 00:00 GMT+8

permissions:
  contents: read

jobs:
  php-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo, pdo_mysql, gd, bcmath # Installs required extensions
          ini-values: memory_limit=-1

      - name: Install project dependencies
        run: |
          composer install --no-scripts --no-progress

      - name: Run Psalm Security Scan
        run: |
          composer require --dev vimeo/psalm
          ./vendor/bin/psalm --report=results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
