name: Psalm Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 16 * * 6' # Every Saturday at 16:00 UTC, which is Sunday 00:00 GMT+8

permissions:
  contents: read

jobs:
  php-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo, pdo_mysql, gd, bcmath # Ensure required extensions are listed
          ini-values: memory_limit=-1
          coverage: none

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev

      - name: Install dependencies
        run: |
          composer install --no-progress --no-suggest
          composer update --prefer-stable --no-suggest

      - name: Psalm Security Scan
        uses: psalm/psalm-github-security-scan@f3e6fd9432bc3e44aec078572677ce9d2ef9c287

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
